import * as Flags from 'country-flag-icons/react/3x2';

export const COUNTRY_CODES: Record<string, keyof typeof Flags> = {
    Bahrain: 'BH',
    'Saudi Arabia': 'SA',
    Australia: 'AU',
    Japan: 'JP',
    China: 'CN',
    USA: 'US',
    Italy: 'IT',
    Monaco: 'MC',
    Canada: 'CA',
    Spain: 'ES',
    Austria: 'AT',
    UK: 'GB',
    Hungary: 'HU',
    Belgium: 'BE',
    Netherlands: 'NL',
    Azerbaijan: 'AZ',
    Singapore: 'SG',
    Mexico: 'MX',
    Brazil: 'BR',
    Qatar: 'QA',
    UAE: 'AE',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'Great Britain': 'GB',
    'Las Vegas': 'US',
    Miami: 'US',
    France: 'FR',
    Germany: 'DE',
    Russia: 'RU',
    Portugal: 'PT',
    Turkey: 'TR',
    'South Africa': 'ZA',
    India: 'IN',
    Korea: 'KR',
    Malaysia: 'MY',
};

export const COUNTRY_CODE_ALIASES: Record<string, keyof typeof Flags> = {
    UK: 'GB',
};

export const NATIONALITY_CODES: Record<string, keyof typeof Flags> = {
    American: 'US',
    Argentine: 'AR',
    Argentinian: 'AR',
    Australian: 'AU',
    Austrian: 'AT',
    Belgian: 'BE',
    Brazilian: 'BR',
    British: 'GB',
    Canadian: 'CA',
    Chinese: 'CN',
    Danish: 'DK',
    Dutch: 'NL',
    Finnish: 'FI',
    French: 'FR',
    German: 'DE',
    Indian: 'IN',
    Irish: 'IE',
    Italian: 'IT',
    Japanese: 'JP',
    Mexican: 'MX',
    Monegasque: 'MC',
    'New Zealander': 'NZ',
    Polish: 'PL',
    Portuguese: 'PT',
    Russian: 'RU',
    'South African': 'ZA',
    Spanish: 'ES',
    Swedish: 'SE',
    Swiss: 'CH',
    Thai: 'TH',
};
